name: News Pipeline

on:
  schedule:
    # 07:00 JST = 22:00 UTC (previous day)
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Show workspace files
        run: |
          pwd
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm i
        working-directory: ${{ github.workspace }}

      - name: Run news pipeline
        run: |
          npm run news
        working-directory: ${{ github.workspace }}

      - name: Commit updated data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data docs/data || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(news): update generated news data"
            git push
          fi
