name: Run Refresh Once on Push

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  run-refresh-once:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install minimal dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedparser beautifulsoup4

      - name: Run integrated collector
        run: |
          python collect_integrated.py

      - name: Build integrated data (Python: X + RSS)
        run: |
          python scripts/integrated_build.py

      - name: Commit updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data docs/data docs || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: refresh daily AI news (manual push)"
            git push
          fi
